//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_QuanLy_NN_KS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAM_CONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHAM_CONG()
        {
            this.CHI_TIET_CHAM_CONG = new HashSet<CHI_TIET_CHAM_CONG>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_NV { get; set; }
        public Nullable<int> ID_REQUEST { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public string TrangThai { get; set; }
    
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
        public virtual REQUEST REQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_CHAM_CONG> CHI_TIET_CHAM_CONG { get; set; }
    }
}
