//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_QuanLy_NN_KS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICH_VU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DICH_VU()
        {
            this.PHONGs = new HashSet<PHONG>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_HOA_DON { get; set; }
        public Nullable<int> ID_PHONG { get; set; }
        public string TenDichVu { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public string DonViTinh { get; set; }
        public string TrangThai { get; set; }
    
        public virtual CHI_TIET_HOA_DON CHI_TIET_HOA_DON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONG> PHONGs { get; set; }
    }
}
