//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_QuanLy_NN_KS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_QL_NN_KSEntities : DbContext
    {
        public DB_QL_NN_KSEntities()
            : base("name=DB_QL_NN_KSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHAM_CONG> CHAM_CONG { get; set; }
        public virtual DbSet<CHI_TIET_CHAM_CONG> CHI_TIET_CHAM_CONG { get; set; }
        public virtual DbSet<CHI_TIET_HOA_DON> CHI_TIET_HOA_DON { get; set; }
        public virtual DbSet<CHUC_VU> CHUC_VU { get; set; }
        public virtual DbSet<CO_SO> CO_SO { get; set; }
        public virtual DbSet<DICH_VU> DICH_VU { get; set; }
        public virtual DbSet<FLOOR> FLOORS { get; set; }
        public virtual DbSet<GIAO_DICH> GIAO_DICH { get; set; }
        public virtual DbSet<HOA_DON> HOA_DON { get; set; }
        public virtual DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public virtual DbSet<KHENTHUONG_KYLUAT_CANHAN> KHENTHUONG_KYLUAT_CANHAN { get; set; }
        public virtual DbSet<KHENTHUONG_KYLUAT_TAPTHE> KHENTHUONG_KYLUAT_TAPTHE { get; set; }
        public virtual DbSet<LOAI_PHONG> LOAI_PHONG { get; set; }
        public virtual DbSet<LOAI_QUYET_DINH> LOAI_QUYET_DINH { get; set; }
        public virtual DbSet<LOAI_REQUEST> LOAI_REQUEST { get; set; }
        public virtual DbSet<NHAN_VIEN> NHAN_VIEN { get; set; }
        public virtual DbSet<PHONG> PHONGs { get; set; }
        public virtual DbSet<PHONG_BAN> PHONG_BAN { get; set; }
        public virtual DbSet<PHU_CAP> PHU_CAP { get; set; }
        public virtual DbSet<QUYET_DINH_CHUC_VU> QUYET_DINH_CHUC_VU { get; set; }
        public virtual DbSet<QUYET_DINH_LUONG> QUYET_DINH_LUONG { get; set; }
        public virtual DbSet<QUYET_DINH_TUYEN_DUNG> QUYET_DINH_TUYEN_DUNG { get; set; }
        public virtual DbSet<QUYETDINH_KHENTHUONG_KYLUAT> QUYETDINH_KHENTHUONG_KYLUAT { get; set; }
        public virtual DbSet<REQUEST> REQUESTs { get; set; }
        public virtual DbSet<TAI_KHOAN> TAI_KHOAN { get; set; }
    }
}
