//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_QuanLy_NN_KS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAN_VIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHAN_VIEN()
        {
            this.CHAM_CONG = new HashSet<CHAM_CONG>();
            this.CHI_TIET_CHAM_CONG = new HashSet<CHI_TIET_CHAM_CONG>();
            this.KHENTHUONG_KYLUAT_CANHAN = new HashSet<KHENTHUONG_KYLUAT_CANHAN>();
            this.QUYET_DINH_CHUC_VU = new HashSet<QUYET_DINH_CHUC_VU>();
            this.QUYET_DINH_LUONG = new HashSet<QUYET_DINH_LUONG>();
        }
    
        public int ID { get; set; }
        public string TenNV { get; set; }
        public string CMND_CCCD { get; set; }
        public Nullable<System.DateTime> NgayThangNamSinh { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHAM_CONG> CHAM_CONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_CHAM_CONG> CHI_TIET_CHAM_CONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHENTHUONG_KYLUAT_CANHAN> KHENTHUONG_KYLUAT_CANHAN { get; set; }
        public virtual QUYET_DINH_TUYEN_DUNG QUYET_DINH_TUYEN_DUNG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUYET_DINH_CHUC_VU> QUYET_DINH_CHUC_VU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUYET_DINH_LUONG> QUYET_DINH_LUONG { get; set; }
        public virtual TAI_KHOAN TAI_KHOAN { get; set; }
    }
}
