//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_QuanLy_NN_KS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG_BAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONG_BAN()
        {
            this.KHENTHUONG_KYLUAT_TAPTHE = new HashSet<KHENTHUONG_KYLUAT_TAPTHE>();
            this.QUYET_DINH_TUYEN_DUNG = new HashSet<QUYET_DINH_TUYEN_DUNG>();
        }
    
        public int ID { get; set; }
        public string TenPhongBan { get; set; }
        public string LienHe { get; set; }
        public string TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHENTHUONG_KYLUAT_TAPTHE> KHENTHUONG_KYLUAT_TAPTHE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUYET_DINH_TUYEN_DUNG> QUYET_DINH_TUYEN_DUNG { get; set; }
    }
}
