//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_QuanLy_NN_KS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHU_CAP
    {
        public int ID { get; set; }
        public string TenPhuCap { get; set; }
        public Nullable<decimal> SoTienPhuCap { get; set; }
        public string TrangThai { get; set; }
    }
}
