//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_QuanLy_NN_KS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYET_DINH_LUONG
    {
        public int ID { get; set; }
        public Nullable<int> ID_NHAN_VIEN { get; set; }
        public Nullable<decimal> MucLuongTheoChucVu { get; set; }
        public Nullable<System.DateTime> NgayApDung { get; set; }
        public string TrangThai { get; set; }
    
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
